# Generated by Django 4.2.7 on 2023-11-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_cartitem_amount_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='owner',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='admin',
            new_name='customer',
        ),
    ]
