# Generated by Django 4.2.7 on 2023-11-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_order_total_price_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
