# Generated by Django 4.2.7 on 2023-11-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_cartitem_name_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
