# Generated by Django 4.2.7 on 2023-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
