# Generated by Django 4.2.7 on 2023-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_remove_paymentdetails_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
