# Generated by Django 4.2.7 on 2023-11-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', serialize=False, to='store_app.cart'),
        ),
    ]
