# Generated by Django 4.2.7 on 2023-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_alter_order_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
