# Generated by Django 4.2.7 on 2023-11-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_feedback_five_feedback_four_feedback_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['product']},
        ),
    ]
