# Generated by Django 4.2.7 on 2023-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='five',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='four',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='one',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='three',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='two',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(5, 'excellent'), (4, 'very good'), (3, 'good'), (2, 'not bad'), (1, 'bad')], default=0),
        ),
    ]
