# Generated by Django 4.2.7 on 2023-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_alter_feedback_options_remove_feedback_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(5, 'excellent'), (4, 'very good'), (3, 'good'), (2, 'not bad'), (1, 'bad')], null=True),
        ),
    ]
