# Generated by Django 4.2.7 on 2023-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_alter_feedback_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
