# Generated by Django 4.2.7 on 2023-11-19 17:16

from django.db import migrations, models
import django.db.models.deletion
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_alter_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'In process'), (2, 'In process. Please add payment_details'), (3, 'In process. Please add shipping_address'), (4, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='store_app.cart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_in_stock',
            field=models.IntegerField(validators=[store_app.models.validate_above_zero]),
        ),
    ]
