# Generated by Django 4.2.7 on 2023-11-19 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_order_id_alter_cart_status_alter_cartitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 23, 6, 33, 646942, tzinfo=datetime.timezone.utc)),
        ),
    ]
