# Generated by Django 4.2.7 on 2023-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0032_rename_created_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
