# Generated by Django 4.2.7 on 2023-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0034_alter_paymentdetails_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
