# Generated by Django 4.2.7 on 2023-12-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0035_alter_paymentdetails_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'In process'), (2, 'In process. Please add payment_details'), (3, 'In process. Please add shipping_address'), (4, 'In process. Please add payment_details and shipping_address'), (5, 'Closed')], default=1),
        ),
    ]
