# Generated by Django 4.2.7 on 2023-12-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0038_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
