# Generated by Django 4.2.7 on 2023-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0039_alter_cart_total_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Paid. In process'), (2, 'In process. Please add payment_details'), (3, 'In process. Please add shipping_address'), (4, 'In process. Please add payment_details and shipping_address'), (5, "Sent to customer's shipping address"), (6, 'Received')], default=1),
        ),
    ]
