# Generated by Django 4.2.7 on 2023-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0042_alter_paymentdetails_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Being processed'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
