# Generated by Django 4.2.7 on 2023-12-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0044_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
